#!/usr/bin/python3
import pymysql
import cgi,cgitb
cgitb.enable()
form = cgi.FieldStorage()
print("Content-type:text/html\r\n\r\n")

id=form.getvalue('sid')
db = pymysql.connect(host="localhost",user="root",password="",database="admin_panel" )
cursor = db.cursor()
cursor.execute("select * from student where s_id='%s'"%(id))
data=cursor.fetchall()
print("<html>")
print("<head>")
print("<title>Update</title>")
print("<link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3' crossorigin='anonymous'>")
print("<link rel='stylesheet' href='css/style.css'>")
print("</head")
print("<body>")
for row in data:
    id=row[0]
    name=row[1]
    email=row[2]
    password=row[3]
    mobile=row[4]
    print("<center>")
    print("<form action='update.py?sid=%d' method='POST'>"%(id))
    print("<input type='hidden' name='sid'>")
    print("<table>")
    print("<tr style='background-color:#d8dfed;'>")
    print("<td colspan='2' style='padding-bottom: 20px;'>")
    print("<label for='update'>UPDATE DETAILS</label>")
    print("</td>")
    print("</tr>")
    print("<tr>")
    print("<td> <label for='name'>Enter Id</label> </td>")
    print("<td> <input type='text' class='input-value' name='id' id='id' value='%s'> </td>"%(id))
    print("</tr>")
    print("<tr>")
    print("<td> <label for='name'>Enter Name</label> </td>")
    print("<td> <input type='text' class='input-value' name='name' id='name' value='%s'> </td>"%(name))
    print("</tr>")
    print("<tr>")
    print("<td> <label for='email'>Enter Email:</label></td>")
    print("<td><input type='email' class='input-value' name='email' id='email' value='%s' ></td>"%(email))
    print("</tr>")
    print("<tr>")
    print("<td><label for='pwd'>Enter Password:</label></td>")
    print("<td> <input type='password' class='input-value' name='pwd' id='pwd' value='%s'> </td>"%(password))
    print("</tr>")
    print("<tr>")
    print("<td><label for='c_pwd'>Re-enter Password:</label></td>")
    print("<td> <input type='password' class='input-value' name='confirm_password' id='pwd' value='%s'> </td>"%(password))
    print("</tr>")
    print("<tr>")
    print("<td> <label for='mobno'>Enter Mobile No.</label> </td>")
    print("<td> <input type='text' class='input-value' name='mobno' id='mobno' value='%s'> </td>"%(mobile))
    print("</tr>")
    print("<tr>")
    print("<td colspan='2' style='padding-bottom: 20px;'><input type='submit' class='btn' name='update' value='SUBMIT'>")
    print("<a href='dashboard.php' class='btn'>BACK</a></td>")
    print("</tr>")
    print("</table>")
    print("</form>")
    print("</center>")
    print("</body>")
    print("</html>")
db.close()